apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dotnet60-basic-shd6
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: var_name
          value: test
        image: quay.io/redhat-appstudio-qe/rs-demos-mhsv-tenant/image-repository-cr-dotnet-component/devfile-sample-dotnet60-basic-shd6@sha256:4de140af0bbe0028a9da449c1392d72dd9cff8765f1398037553586c03e56e9f
        name: main
        resources: {}
status: {}
