apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dotnet60-basic-shd6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dotnet60-basic-shd6
    app.kubernetes.io/part-of: image-repository-cr-dotnet-component
  name: devfile-sample-dotnet60-basic-shd6
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: devfile-dotnet-deploy
      app.kubernetes.io/instance: devfile-sample-dotnet60-basic-shd6
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devfile-dotnet-deploy
        app.kubernetes.io/instance: devfile-sample-dotnet60-basic-shd6
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rs-demos-mhsv-tenant/image-repository-cr-dotnet-component/devfile-sample-dotnet60-basic-shd6@sha256:4de140af0bbe0028a9da449c1392d72dd9cff8765f1398037553586c03e56e9f
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
